version: '3'
services:
  rasa_en:
    image: rasa_test
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - $PWD/data:/app/data
      - $PWD/bot.py:/app/bot.py
    ports:
      - "5005:5005"
    command: python bot.py -d data/servicing-bot-en/models/dialogue -u data/servicing-bot-en/models/servicing-bot-en/model-en --port 5005 -o log_file.log
  rasa_fr:
    image: rasa_test
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - $PWD/data:/app/data
      - $PWD/bot.py:/app/bot.py
    ports:
      - "5006:5006"
    command: python bot.py -d data/servicing-bot-fr/models/dialogue -u data/servicing-bot-fr/models/servicing-bot-fr/model-fr  --port 5006 -o log_file.log
  redis:  
    image: redis
    build:
      context: ./redis
    volumes:
      - ${PWD}/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command : [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

